### ISSUE TITLE
Error when closing dialog

### ISSUE THREAD

**Issue by pcav** [AnotherBobSmith/CLUZ#6]
When closing the "Select or create CLUZ setup file" with Cancel, I get:

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/cluz/cluz_menu.py", line 118, in 
    self.ConvertVecAction.triggered.connect(lambda: self.convertPolylinePolygonToAbundanceData(setupObject))
  File "/home/paolo/.qgis2/python/plugins/cluz/cluz_menu.py", line 214, in convertPolylinePolygonToAbundanceData
    setupObject.abundPUKeyDict = cluz_setup.makeAbundancePUKeyDict(setupObject)
  File "/home/paolo/.qgis2/python/plugins/cluz/cluz_setup.py", line 404, in makeAbundancePUKeyDict
    with open(puvspr2FilePath, 'rb') as f:
IOError: [Errno 2] File o directory non esistente: 'blank/puvspr2.dat'

**Comment by pcav** [comment]
Same for other dialogs. I did not setup the environment, but the error should be handled gracefully.

**Comment by AnotherBobSmith** [comment]
Problem fixed
